export const categories = [
  "SPECIAL",
  "Бургеры",
  "Закуски",
  "Лапша WOK",
  "Супы",
  "Горячее",
  "Салаты",
  "Пицца",
  "Напитки",
  "Чай и кофе",
  "Дополнительно"
];

export const menu = [
  { id: "special-pea-soup", name: "Гороховый крем-суп", description: "Горох, охотничьи колбаски, зелёный лук · 290 г", price: 290, category: "SPECIAL" },
  { id: "special-hot-dog", name: "Хот-дог Special", description: "Свино-говяжья колбаска, шашлычный соус, халапеньо, дижонская горчица, кунжут · 200 г", price: 340, category: "SPECIAL", spicy: true },
  { id: "special-chicken-quesadilla", name: "Кесадилья с курицей", description: "Тортилья, куриное бедро, шампиньоны, чеддер, кинза · 290 г", price: 500, category: "SPECIAL" },
  { id: "special-zucchini-burger", name: "Zucchini Burger", description: "Мраморная говядина, чеддер, томаты, огурцы, красный лук, бекон, кабачковый соус · 320 г", price: 730, category: "SPECIAL", image: "burger" },
  { id: "special-spinach-pizza", name: "Пицца со шпинатом", description: "Скаморца, бекон, вяленая индейка, сливочно-шпинатный соус · 450 г", price: 880, category: "SPECIAL", image: "pizza" },
  { id: "special-arugula-shrimp", name: "Салат с рукколой и креветками", description: "Томаты черри, огурцы, киноа, медово-бальзамический соус · 200 г", price: 680, category: "SPECIAL" },

  { id: "burger-saldens", name: "Salden’s Burger", description: "Мраморная говядина, томаты, чеддер, красный лук, огурцы, чесночный и BBQ соусы · 300 г", price: 720, category: "Бургеры", image: "burger" },
  { id: "burger-steak", name: "Steak Burger", description: "Стейк флап, томаты, маринованные огурцы, кунжут, шашлычный соус · 200 г", price: 890, category: "Бургеры" },
  { id: "burger-peanut", name: "Peanut Burger", description: "Мраморная говядина, чеддер, бекон, луковый мармелад и арахисовая паста · 300 г", price: 690, category: "Бургеры" },
  { id: "burger-chicken", name: "Chicken Burger", description: "Куриная котлета, чеддер, ананас, томаты, гуакамоле, чили-майо · 330 г", price: 720, category: "Бургеры" },
  { id: "burger-paradise", name: "Paradise Burger", description: "Мраморная говядина, чеддер, бекон, томаты, куриное яйцо и маринованные огурцы · 350 г", price: 830, category: "Бургеры" },
  { id: "burger-dry-age", name: "Dry Age Burger", description: "Ферментированная мраморная говядина, бекон, сыр бри и брусничный соус · 300 г", price: 870, category: "Бургеры" },
  { id: "burger-blue-cheese", name: "Blue Cheese Burger", description: "Мраморная говядина, чеддер, бекон, лук фри, дор блю и ежевичный соус · 300 г", price: 780, category: "Бургеры" },
  { id: "burger-pulled-pork", name: "Pulled Pork Burger", description: "Рваная свинина, чеддер, бекон, халапеньо, карамелизированный лук · 330 г", price: 680, category: "Бургеры", spicy: true },
  { id: "burger-rhcb", name: "RHCB", description: "Мраморная говядина, чеддер, бекон, халапеньо, карамелизированный лук, соус пири-пири · 320 г", price: 740, category: "Бургеры", spicy: true },
  { id: "burger-apricot", name: "Apricot Burger", description: "Мраморная говядина, чеддер, красный лук, айсберг, томаты, бекон, абрикосово-горчичный соус · 350 г", price: 720, category: "Бургеры" },

  { id: "snack-dried-beef", name: "Вяленая говядина", description: "100 г", price: 590, category: "Закуски" },
  { id: "snack-dried-pork", name: "Вяленая свинина", description: "100 г", price: 390, category: "Закуски" },
  { id: "snack-dried-turkey", name: "Вяленая индейка", description: "100 г", price: 440, category: "Закуски" },
  { id: "snack-chechil", name: "Сыр чечил", description: "100 г", price: 310, category: "Закуски" },
  { id: "snack-scamorza", name: "Сыр скаморца копчёный", description: "100 г", price: 340, category: "Закуски" },
  { id: "snack-poutine", name: "Poutine", description: "Картофель фри с сырным соусом, креветками, беконом и зелёным луком · 370 г", price: 770, category: "Закуски" },
  { id: "snack-pulled-pork-poutine", name: "Pulled Pork Poutine", description: "Картофель фри с рваной свининой, карамелизированным луком, беконом и BBQ · 400 г", price: 670, category: "Закуски" },
  { id: "snack-wings", name: "Куриные крылья", description: "С зелёным луком, кунжутом и сладким чили · 300 г", price: 640, category: "Закуски" },
  { id: "snack-ribs", name: "Свиные рёбра", description: "С луком фри, кунжутом и BBQ соусом · 320 г", price: 790, category: "Закуски", spicy: true },
  { id: "snack-nachos", name: "Начос", description: "С беконом, гуакамоле, сырным и спайси соусами · 300 г", price: 590, category: "Закуски", spicy: true },
  { id: "snack-tempura-shrimp", name: "Креветки темпура", description: "В панировке с тайским соусом · 150 г", price: 490, category: "Закуски" },
  { id: "snack-fish-chips", name: "Fish & Chips", description: "Филе трески, картофель фри, тартар, кетчуп · 330 г", price: 630, category: "Закуски" },
  { id: "snack-nuggets", name: "Наггетсы", description: "Из индейки с соусом чили-майо · 200 г", price: 490, category: "Закуски", spicy: true },
  { id: "snack-strips", name: "Стрипсы", description: "Куриные, с дижонской горчицей · 200 г", price: 460, category: "Закуски" },
  { id: "snack-hotdog", name: "Хот-дог", description: "Сосиска в беконе, томаты, огурцы, лук фри, салат из капусты, соусы · 500 г", price: 540, category: "Закуски" },
  { id: "snack-caciotta", name: "Сыр качотта", description: "Полутвёрдый сыр в панировке со спайси соусом · 180 г", price: 540, category: "Закуски", spicy: true },
  { id: "snack-suluguni", name: "Сыр сулугуни", description: "Мягкий сыр в панировке с ежевичным соусом · 240 г", price: 590, category: "Закуски" },
  { id: "snack-hummus-bacon", name: "Хумус с беконом", description: "Пита, халапеньо, семечки, лимон, паприка и кинза · 350 г", price: 400, category: "Закуски" },
  { id: "snack-hummus-mushroom", name: "Хумус грибной", description: "Пита, гранат, семечки, лимон, паприка и кинза · 350 г", price: 400, category: "Закуски" },
  { id: "snack-potato-balls", name: "Картофельные шарики", description: "С начос, халапеньо, беконом, горчичным соусом и гуакамоле · 240 г", price: 470, category: "Закуски" },

  { id: "wok-wheat", name: "Пшеничный WOK", description: "Говядина, овощи, шиитаке, кунжут, соевый соус и кимчи · 310 г", price: 760, category: "Лапша WOK", spicy: true },
  { id: "wok-buckwheat", name: "Гречневый WOK", description: "Креветки, кальмары, индейка, овощи, шиитаке, кунжут, сливки и соевый соус · 330 г", price: 660, category: "Лапша WOK" },

  { id: "soup-ramen", name: "Рамен", description: "Копчёный свиной бок, бекон, яйцо, пшеничная лапша, шиитаке и зелёный лук · 300 г", price: 310, category: "Супы" },
  { id: "soup-thai", name: "Тайский суп", description: "Кокосовое молоко, тигровые креветки, рисовая лапша, черри, вешенки и зелёный лук · 300 г", price: 450, category: "Супы", spicy: true },
  { id: "soup-mushroom", name: "Грибной крем-суп", description: "Белые грибы, шампиньоны, вешенки, сливки, зелёный лук и гренки · 300 г", price: 320, category: "Супы" },

  { id: "hot-flap-steak", name: "Стейк флап", description: "Мраморная говядина на гриле, картофельные дольки, шашлычный соус и кетчуп · 330 г", price: 1450, category: "Горячее" },
  { id: "hot-striploin", name: "Стейк стриплойн", description: "Мраморная говядина на гриле, картофельные дольки, шашлычный соус и кетчуп · 350 г", price: 1600, category: "Горячее" },
  { id: "hot-beef-quesadilla", name: "Кесадилья с говядиной", description: "Мраморная говядина, фасоль, кукуруза, овощи, чеддер и скаморца · 330 г", price: 670, category: "Горячее", spicy: true },
  { id: "hot-stracciatella-quesadilla", name: "Кесадилья со страчателлой", description: "Тортилья, копчёный свиной бок, чеддер, страчателла, халапеньо, шрирача и гуакамоле · 330 г", price: 690, category: "Горячее", spicy: true },
  { id: "hot-sausages", name: "Колбаски на выбор", description: "Охотничьи или мексиканские; с капустным салатом, овощами, картофельными дольками, горчицей, кетчупом · 360 г", price: 480, category: "Горячее" },
  { id: "hot-sausage-xxl", name: "Колбаска XXL", description: "С капустным салатом, овощами, картофельными дольками, горчицей, кетчупом и зелёным луком · 450 г", price: 630, category: "Горячее" },
  { id: "hot-pork-ears", name: "Копчёные свиные уши", description: "С бородинским хлебом, овощами кимчи, кунжутом и зелёным луком · 270 г", price: 420, category: "Горячее", spicy: true },

  { id: "salad-salmon", name: "Салат с лососем", description: "Слабосолёный лосось, черри, огурцы, яйцо, творожный сыр, айсберг и оливковое масло · 300 г", price: 770, category: "Салаты" },
  { id: "salad-caesar-turkey", name: "Цезарь с индейкой", description: "Индейка, пармезан, печёные томаты, айсберг, гренки и соус цезарь · 180 г", price: 500, category: "Салаты" },
  { id: "salad-caesar-shrimp", name: "Цезарь с креветками", description: "Креветки, пармезан, печёные томаты, айсберг, гренки и соус цезарь · 180 г", price: 550, category: "Салаты" },
  { id: "salad-sausages", name: "Салат с колбасками", description: "Охотничьи колбаски, картофельные дольки, айсберг, огурцы, черри, зелёный лук и соус релиш · 300 г", price: 450, category: "Салаты" },

  { id: "pizza-turkey-bbq", name: "Индейка BBQ", description: "Индейка, бекон, скаморца, перец, руккола, томатный и BBQ соусы · 590 г", price: 1070, category: "Пицца", image: "pizza" },
  { id: "pizza-cheese", name: "Сырная", description: "Дор блю, скаморца, бри, чеддер и пармезан; руккола и томатный соус · 540 г", price: 1090, category: "Пицца" },
  { id: "pizza-pulled-pork", name: "Pulled Pork", description: "Рваная свинина, скаморца, халапеньо, огурцы, карамелизированный лук, руккола, BBQ и пири-пири · 520 г", price: 940, category: "Пицца", spicy: true },
  { id: "pizza-pepperoni", name: "Пеперони", description: "Пеперони, скаморца, руккола, томатный соус · 470 г", price: 840, category: "Пицца" },
  { id: "pizza-mortadella", name: "Мортаделла", description: "Мортаделла, скаморца, страчателла, фисташки, руккола и томатный соус · 520 г", price: 910, category: "Пицца" },
  { id: "pizza-sausages", name: "Пицца с колбасками", description: "Мексиканская колбаска, скаморца, бекон, огурцы, оливки, маслины, руккола и соусы · 650 г", price: 890, category: "Пицца" },

  { id: "drink-lemonade", name: "Лимонад Черноголовка", description: "В ассортименте · 500 мл", price: 250, category: "Напитки" },
  { id: "drink-water", name: "Вода Черноголовка", description: "В ассортименте · 330 мл", price: 200, category: "Напитки" },
  { id: "drink-juice", name: "Сок", description: "В ассортименте · 250 мл", price: 150, category: "Напитки" },

  { id: "tea-assam", name: "Ассам", description: "500 мл", price: 300, category: "Чай и кофе" },
  { id: "tea-earl-grey", name: "Эрл Грей", description: "500 мл", price: 300, category: "Чай и кофе" },
  { id: "tea-sencha", name: "Сенча", description: "500 мл", price: 300, category: "Чай и кофе" },
  { id: "tea-milk-oolong", name: "Молочный улун", description: "500 мл", price: 300, category: "Чай и кофе" },
  { id: "coffee-espresso", name: "Эспрессо", description: "60 мл", price: 110, category: "Чай и кофе" },
  { id: "coffee-double-espresso", name: "Двойной эспрессо", description: "120 мл", price: 170, category: "Чай и кофе" },
  { id: "coffee-americano", name: "Американо", description: "200 мл", price: 160, category: "Чай и кофе" },
  { id: "coffee-cappuccino", name: "Капучино", description: "200 мл", price: 180, category: "Чай и кофе" },
  { id: "coffee-latte", name: "Латте", description: "250 мл", price: 220, category: "Чай и кофе" },

  { id: "extra-sauce", name: "Дополнительный соус", description: "Спайси, чесночный, пири-пири, релиш, сырный, сладкий чили, BBQ, ежевичный, брусничный, кетчуп, чили-майо, шашлычный, гуакамоле, дор блю, горчица, тартар или халапеньо · 30 г", price: 50, category: "Дополнительно" }
];
