const POSITIVE_PATTERNS=[[/ceasefire (agreed|agreement|deal)|agreed (to )?a ceasefire/i,16],[/peace (deal|agreement) (is )?(close|near)|deal (is )?(close|near)/i,13],[/resume(d)? (peace )?(talks|negotiations)|talks (resume|resumed)/i,9],[/peace talks|peace negotiations|negotiations/i,6],[/leader(s)? (to )?meet|summit|direct talks/i,6],[/proposal(s)? (for|to) (ending|end) the war|peace proposal|peace plan/i,5],[/security guarantees?/i,3],[/prisoner exchange|exchange of prisoners/i,2]];
const NEGATIVE_PATTERNS=[[/no (immediate )?prospect|no prospect of resuming/i,-15],[/talks? (stalled|collapse|collapsed|fail|failed)|deadlock|impasse/i,-11],[/reject(s|ed)? (a )?(ceasefire|peace plan|proposal|deal)/i,-10],[/strike(s|d)?|drone attack|missile attack|bombardment/i,-5],[/offensive|advance(s|d)?|escalat(e|es|ed|ion)/i,-4],[/ultimatum|threaten(s|ed)?|raise the stakes/i,-3]];
const $=id=>document.getElementById(id);
const ui={probability:$('probability'),mood:$('mood'),meterFill:$('meterFill'),meterMarker:$('meterMarker'),timestamp:$('timestamp'),button:$('refreshButton'),positive:$('positiveCount'),negative:$('negativeCount'),neutral:$('neutralCount'),news:$('newsList'),error:$('errorNote')};
function cleanTitle(title){return String(title||'').replace(/\s+/g,' ').trim()}
function scoreTitle(title){let score=0;for(const [p,n] of POSITIVE_PATTERNS){if(p.test(title))score+=n}for(const [p,n] of NEGATIVE_PATTERNS){if(p.test(title))score+=n}return Math.max(-18,Math.min(18,score))}
function isRelevant(title){const s=title.toLowerCase();const party=s.includes('ukrain')||s.includes('russia')||s.includes('kyiv')||s.includes('moscow');const signal=/(peace|ceasefire|talk|negotiat|deal|proposal|summit|strike|attack|offensive|escalat|ultimatum|security guarantee)/i.test(title);return party&&signal}
function parseSeenDate(value){if(!value)return null;const m=String(value).match(/^(\d{4})(\d{2})(\d{2})T?(\d{2})?(\d{2})?/);if(!m)return null;return new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+(m[4]||0),+(m[5]||0)))}
function freshnessWeight(date){if(!date)return .45;const hours=Math.max(0,(Date.now()-date.getTime())/3600000);return Math.max(.35,1-hours/(24*11))}
function selectArticles(raw){const seen=new Set(),domainCounts=new Map(),items=[];for(const a of raw||[]){if(!a.title||!a.url)continue;const title=cleanTitle(a.title);if(!isRelevant(title))continue;const key=title.toLowerCase().replace(/[^a-zа-яё0-9]+/gi,' ').trim();if(seen.has(key))continue;let domain=a.domain;try{domain=domain||new URL(a.url).hostname.replace(/^www\./,'')}catch{domain=domain||'источник'}const count=domainCounts.get(domain)||0;if(count>=3)continue;const score=scoreTitle(title);items.push({title,url:a.url,domain,date:parseSeenDate(a.seendate),score,signal:score>=3?'positive':score<=-3?'negative':'neutral'});seen.add(key);domainCounts.set(domain,count+1);if(items.length>=18)break}return items}
function calculateProbability(items){if(!items.length)return 50;let weighted=0,total=0;for(const item of items){const w=freshnessWeight(item.date);weighted+=item.score*w;total+=w}const avg=total?weighted/total:0;return Math.round(Math.max(8,Math.min(92,50+avg*2.15)))}
function mood(p){if(p>=65)return'Переговорный вайб усиливается';if(p>=50)return'Осторожный перевес в сторону диалога';if(p>=35)return'Пока скорее туман, чем мир';return'Новостной фон выглядит жёстко'}
function formatDate(d){if(!d)return'дата не указана';return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(items,p){const positive=items.filter(x=>x.signal==='positive').length,negative=items.filter(x=>x.signal==='negative').length,neutral=items.length-positive-negative;ui.probability.textContent=`${p}%`;ui.mood.textContent=mood(p);ui.meterFill.style.width=`${p}%`;ui.meterMarker.style.left=`${p}%`;ui.positive.textContent=positive;ui.negative.textContent=negative;ui.neutral.textContent=neutral;ui.timestamp.textContent=`Проверено: ${new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'medium'}).format(new Date())}`;if(!items.length){ui.news.innerHTML='<div class="empty">Свежих релевантных публикаций не нашлось.</div>';return}ui.news.innerHTML=items.map(a=>`<a class="news-card" href="${escapeHtml(a.url)}" target="_blank" rel="noreferrer"><div class="signal ${a.signal}">${a.signal==='positive'?'↑ к миру':a.signal==='negative'?'↓ от мира':'• нейтр.'}</div><div class="news-body"><h3>${escapeHtml(a.title)}</h3><div class="news-meta"><span>${escapeHtml(a.domain)}</span><span>·</span><span>${formatDate(a.date)}</span><span>·</span><span>балл ${a.score>0?'+':''}${a.score}</span></div></div><span class="arrow">↗</span></a>`).join('')}
async function loadForecast(){ui.button.disabled=true;ui.button.textContent='Ищу новости…';ui.error.classList.add('hidden');try{const params=new URLSearchParams({query:'ukraine (peace OR ceasefire OR negotiations OR talks OR deal OR proposal OR summit OR strikes OR attack OR offensive)',mode:'artlist',format:'json',maxrecords:'100',timespan:'7d',sort:'DateDesc',_t:String(Date.now())});const res=await fetch(`https://api.gdeltproject.org/api/v2/doc/doc?${params}`,{cache:'no-store'});if(!res.ok)throw new Error(`GDELT HTTP ${res.status}`);const data=await res.json();const items=selectArticles(data.articles||[]);render(items,calculateProbability(items))}catch(err){render([],50);ui.error.textContent='Источник новостей временно недоступен. Показано нейтральное значение 50%. '+(err instanceof Error?err.message:'');ui.error.classList.remove('hidden')}finally{ui.button.disabled=false;ui.button.textContent='Обновить прогноз'}}
ui.button.addEventListener('click',loadForecast);loadForecast();
